name: Tauri Build

on:
    push:
        tags:
            - 'v*'
    workflow_dispatch:

jobs:
    build:
        timeout-minutes: 120
        strategy:
            fail-fast: false
            matrix:
                include:
                    - os: ubuntu-22.04
                      target: x86_64-unknown-linux-gnu
                    - os: windows-latest
                      target: x86_64-pc-windows-msvc
                    - os: macos-latest
                      target: x86_64-apple-darwin
                    - os: macos-latest
                      target: aarch64-apple-darwin  # Apple Silicon

        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v4

            -   name: Setup Node
                uses: actions/setup-node@v4
                with:
                    node-version: 25

            -   name: Setup Rust
                uses: dtolnay/rust-toolchain@stable
                with:
                    targets: ${{ matrix.target }}

            -   name: Cache Rust
                uses: swatinem/rust-cache@v2
                with:
                    workspaces: src-tauri

            -   name: Install Linux dependencies
                if: matrix.os == 'ubuntu-22.04'
                run: |
                    sudo apt update
                    sudo apt install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

            -   name: Enable Corepack
                run: corepack enable

            -   name: Prepare Yarn 4
                run: corepack prepare yarn@4.13.0 --activate

            -   name: Get yarn cache directory
                id: yarn-cache-dir
                run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
                shell: bash

            -   name: Cache yarn
                uses: actions/cache@v4
                with:
                    path: ${{ steps.yarn-cache-dir.outputs.dir }}
                    key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                    restore-keys: ${{ runner.os }}-yarn-

            -   name: Install dependencies
                run: yarn install

            - name: Build Tauri
              uses: tauri-apps/tauri-action@v0
              with:
                  args: --target ${{ matrix.target }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: tauri-${{ matrix.os }}-${{ matrix.target }}
                  path: |
                      src-tauri/target/${{ matrix.target }}/release/bundle/
